### PR TITLE
Make Visual Studio solution build

### PR DESCRIPTION
**Pull request by katacode**
Also, I bumped the project version/toolset to 2017 and added include paths for gtest.

### CODE REVIEW

**Comment by katacode** [comment]
I don't know why all those other commits show up, but they don't contribute any changes according to the diffs (they've all been reverted or merged already).

**Comment by deplinenoise** [comment]
Can you rebase on latest (Aras just cleaned up the 2012 version) so we get rid of the extra commits? Cheers!

**Comment by deplinenoise** [comment]
Handling this in #298

**Comment by katacode** [comment]
Thanks! My git fu is weak :(

**Pull request closed without merging**
